src/l10n/nb.json, src/pages/dataset-registration-page/form-distribution/__snapshots__/form-distribution-pure.test.jsx.snap, src/pages/dataset-registration-page/form-distribution/distribution-types.js, src/pages/dataset-registration-page/form-distribution/form-distribution-pure.jsx, test/fixtures/distributions.js
=> feat: add distribution title

src/pages/dataset-registration-page/field-tagsinput-apis/field-tagsinput-apis.component.jsx, src/pages/dataset-registration-page/form-distribution/form-distribution-pure.tsx
Har endre accessService på distribusjon fra object til liste av objekter.
Forsøkte å gjenskape migrering lokalt flere ganger og det ser ut at ES klarer å takle endring i modellen ganske greit (pga reindeksering logikk ved oppstart).
=> feat: #17 change accessService type to list

package-lock.json, src/pages/catalogs-page/__snapshots__/catalogs-page.test.jsx.snap, src/pages/catalogs-page/catalogs-page-pure.tsx
NB! Reviewer må oppdatere snapshots - og merge i vei!
=> updated terms and condition warning

src/pages/catalogs-page/catalogs-page-pure.tsx
Reviewer kan godt merge også :)
=> lenke går nå mot data.norge

src/components/list-items/__snapshots__/list-items.test.jsx.snap, src/components/list-items/list-item/__snapshots__/list-item.test.jsx.snap, src/components/list-items/list-item/list-item.component.jsx, src/components/list-items/list-item/list-item.test.jsx, src/components/list-items/list-items.component.jsx, src/components/list-items/list-items.test.jsx, src/l10n/nb.json
Rebases last modified sort on datasets. 
(cherry picked from commit c0745629aae97590c11b94569a185d17f37ed839)
=> feat: adds last modified column

src/l10n/helptexts.nb.js
updated some helptexts to point directly to specc
=> Change helptexts dataset

src/components/helptext/helptext.component.jsx, src/pages/dataset-registration-page/form-concept/__snapshots__/form-concept-pure.component.test.jsx.snap, src/pages/dataset-registration-page/form-concept/form-concept-pure.component.jsx, src/pages/dataset-registration-page/form-contactPoint/__snapshots__/form-contactPoint.test.jsx.snap, src/pages/dataset-registration-page/form-contactPoint/form-contactPoint.component.jsx, src/pages/dataset-registration-page/form-distribution/form-distribution-pure.tsx, src/pages/dataset-registration-page/form-los/form-los.component.jsx, src/pages/dataset-registration-page/form-reference/__snapshots__/form-reference.test.jsx.snap, src/pages/dataset-registration-page/form-reference/form-reference.component.jsx, src/pages/dataset-registration-page/form-spatial/__snapshots__/form-spatial.test.jsx.snap, src/pages/dataset-registration-page/form-spatial/form-spatial.component.jsx
closes Informasjonsforvaltning/fdk-issue-tracker#200
=> fix: adds required and recommended badges to helptexts

src/l10n/helptexts.nb.js
=> fix: update spesification text

src/services/api/registration-api/datasets.js
=> fix: #145 use correct access property for datasets count

src/services/translations/documents/helptexts.nb.js
Update description with formål
=> fix: update helptext for description with formål

src/components/form-reference/form-reference-validations.js
=> fix: #161 fix validation bug on URI field

package-lock.json, package.json, src/services/api/records-registration-api/host.js
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/354
Svaret fra backend er paginert, endret fra 10 til 1000 per side:
=> fix: get correct records count

package-lock.json, src/components/form-theme/form-theme.component.tsx, src/services/translations/documents/nb.json
=> remove eu-theme deprecation message

src/components/field-tagsinput-apis/index.tsx
=> chore: save access service uri

package-lock.json, package.json
Part of Informasjonsforvaltning/fdk-admin-gui#108
=> chore: bump demo logo

audit-resolve.json, package-lock.json, src/services/translations/documents/helptexts.nb.js, src/services/translations/documents/nb.json
=> update access right texts

src/services/translations/documents/helptexts.nb.js
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/502
=> chore: update license help text

.github/workflows/deploy-demo.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml, audit-resolve.json, nginx.conf, package-lock.json, package.json, src/components/catalog/index.tsx, src/entrypoints/main/router/catalogs/pages/overview-page/index.tsx, src/entrypoints/main/router/datasets/pages/dataset-page/index.tsx, src/entrypoints/main/router/datasets/pages/datasets-page/index.tsx, src/services/translations/documents/nb.json, webpack/base.config.ts, webpack/dev.config.ts
resolve https://github.com/Informasjonsforvaltning/registration-portal/issues/2
=> chore: remove external catalogs from catalog overview

audit-resolve.json, package-lock.json, package.json, src/entrypoints/main/router/datasets/pages/dataset-page/index.tsx, src/entrypoints/main/router/datasets/pages/datasets-page/index.tsx
=> hide overview-page from breadcrumbs

src/entrypoints/main/router/index.tsx
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/602
=> fix: show all catalogs at /catalogs

src/components/with-reference-data/redux/saga.ts
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/609
=> chore: change new-reference-data to reference-data

src/components/dataset-registration-form/formsLib/asyncValidateDatasetInvokePatch.js, src/components/dataset-registration-form/index.tsx
=> fix: enable publish

package-lock.json, package.json, src/components/dataset-search/styled.ts, src/components/spinner/index.tsx, src/pages/datasets-page/populated-table.tsx, src/pages/datasets-page/styled.ts, src/utils/styles/break-point.ts
resolves https://github.com/Informasjonsforvaltning/dataset-catalog-gui/issues/373
=> feat/por/responsive UI

Dockerfile, package-lock.json, package.json
resolves https://github.com/Informasjonsforvaltning/dataset-catalog-gui/issues/394
=> chore: bump node to 18.12.1

src/components/table/table-row/styled.ts
=> fix: use cursor pointer on hover

.storybook/main.js
=> chore: disable storybook telemetry

package.json, src/pages/datasets-page/index.tsx, src/utils/authentication/index.ts
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/697
=> fix: disable add button for readonly user

src/utils/language/nb.ts
correct word dataset to datasett
=> fix: correct word dataset to datasett

package-lock.json, package.json, src/context/actions.ts, src/context/datasets-context/api-front-back.ts, src/context/datasets-context/index.tsx, src/context/datasets-context/reducer.ts, src/pages/datasets-page/index.tsx, src/utils/language/nb.ts
fixes https://github.com/Informasjonsforvaltning/dataset-catalog-gui/issues/480#issuecomment-1909963931
=> fix: show correct org name

package-lock.json, package.json
related to https://github.com/Informasjonsforvaltning/sso/issues/147
=> chore: bump keycloak

src/utils/authentication/auth-service.ts
authService was referring to wrong silent-check-sso.html path.
=> fix: app is available on path /catalogs not / (root)
